### ISSUE TITLE
REQUEST: Any chance these might work with Poison Potatoes?

### ISSUE THREAD

**Issue by Wytchcat** [r1ckypotato/SpudGun#1]
I have several players who want  use for poison potatoes on our 1.21 server.

As you know.. there isn't really one. I've looked and while doing so realized .. a Spud Gun seems like a go to.

Any chance we could make that a thing?

Thanks!
Wytch's Lair Admin

**Comment by r1ckypotato** [comment]
In the current version of spud gun poisonous potatoes only shoot about 2 blocks and barley do any damage.

If you would like I can make an updated version of spud gun where poisonous potatoes shoot further, do the same damage as regular potatoes and give the poison effect for a few seconds. (**Will shoot a bit shorter distance than regular potatoes**)

I can also make the crafting recipes easier if you would like because currently the crafting recipe for the **Spud Gun** uses 5 Netherite Ingots and the **Spud Machine Gun** uses 1 Netherite block and 4 Netherite Ingots.

Let me know if you all that sounds good to you and if the recipes are good how they are or if you would like me to change them. 

-R1ckyPotato

**Comment by Wytchcat** [comment]
Hi there!

That would be great!  

I have a mixed server where some play creative and some survival so the crafting recipe change might be nice.  Maybe add a new one and make the current one an achievement?  

I sort of think this might also get you some more downloads... I could be wrong though.

**Comment by r1ckypotato** [comment]
Hi, yeah it probably will get more downloads and this is actually something I was gonna add but kind of forgot about.

How about I could make the Machine gun have the same recipe as the current Spud Gun and make the Spud Gun with 1 Netherite Ingot and maybe some Iron or something like that?

**Comment by Wytchcat** [comment]
That could work.

**Comment by Wytchcat** [comment]
Thanks! I'll send along any feedback!
